# Source https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/examples/deploy-on-pushing-a-new-tag.yml
name: Deploy to WordPress.org
on:
  push:
    # Only run when tag is pushed
    tags:
      - 'v*.*.*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
        uses: php-actions/composer@v4
        with:
          dev: no
          composer_version: 2
          args: --ignore-platform-reqs --no-scripts --no-cache
          php_version: 7.4
          ssh_key: ${{ secrets.SSH_KEY_FOR_NETCASH_PAYNOW_PHP }}
          ssh_key_pub: ${{ secrets.SSH_KEY_FOR_NETCASH_PAYNOW_PHP_PUBLIC }}
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        # SVN URL: https://plugins.svn.wordpress.org/netcash-pay-now-payment-gateway-for-woocommerce
        # WP Plugin URL: https://wordpress.org/plugins/netcash-pay-now-payment-gateway-for-woocommerce
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: netcash-pay-now-payment-gateway-for-woocommerce
